server:
  port: 80

spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: tutor-register:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://tutor-mysql:3306/tutor_auth?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    host: tutor-redis
    port: 6379
    password: root
  mail:
      host: smtp.qq.com
      port: 587
      username:
      password:

security:
  oauth2:
    client:
      client-id: auth
      client-secret: auth
      user-authorization-uri: http://tutor-gateway:9920/auth/oauth/authorize
      access-token-uri: http://tutor-gateway:9920/auth/oauth/token

juchia:
  security:
    social:
      qq:
        app-id:
        app-secret:
        providerId: qq

logging:
  level:
    root: info